<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import { BarChartOutlined, BulbOutlined, CloudUploadOutlined, DatabaseOutlined, EditOutlined, FileTextOutlined, RadarChartOutlined } from '@ant-design/icons-vue';
import { api, type Brand, type ContentItem, type Detection, type Opportunity, type Prompt, type Publication, type VisibilitySummary } from './api';

const active = ref('overview'); const loading = ref(false); const error = ref('');
const brands = ref<Brand[]>([]); const prompts = ref<Prompt[]>([]); const detections = ref<Detection[]>([]);
const summary = ref<VisibilitySummary>({ sampleSize: 0, mentionRate: null, averageRank: null, citationCount: 0, citationDomains: [] });
const brandForm = reactive({ name: '', website: '', aliases: '' });
const promptForm = reactive({ question: '', intent: 'commercial', priority: 50, tags: '' });
const selectedPrompt = ref<string>(); const selectedBrand = ref<string>();
const opportunityBrand = ref<string>(); const opportunities = ref<Opportunity[]>([]);
const contents = ref<ContentItem[]>([]); const publications = ref<Publication[]>([]);
const contentForm = reactive({ brandId: '', promptId: '', title: '', bodyMarkdown: '', evidenceUrls: '' });
const publishForm = reactive({ contentId: '', platform: 'zhihu', account: '' }); const exportPreview = ref('');
const menu = [
  { key: 'overview', label: '数据总览', icon: BarChartOutlined }, { key: 'brands', label: '品牌资产', icon: DatabaseOutlined },
  { key: 'prompts', label: 'Prompt 管理', icon: FileTextOutlined }, { key: 'monitor', label: 'AI 可见度', icon: RadarChartOutlined },
  { key: 'opportunities', label: '机会中心', icon: BulbOutlined },
  { key: 'contents', label: '内容工坊', icon: EditOutlined }, { key: 'publishing', label: '发布中心', icon: CloudUploadOutlined },
];
const title = computed(() => menu.find((item) => item.key === active.value)?.label ?? '数据总览');
async function refresh() { loading.value = true; error.value = ''; try { [brands.value, prompts.value, detections.value, summary.value, contents.value, publications.value] = await Promise.all([api.brands(), api.prompts(), api.detections(), api.visibility(), api.contents(), api.publications()]); } catch (reason) { error.value = reason instanceof Error ? reason.message : '加载失败'; } finally { loading.value = false; } }
async function createBrand() { await api.createBrand({ name: brandForm.name, website: brandForm.website || null, aliases: brandForm.aliases.split(',').map((x) => x.trim()).filter(Boolean) }); Object.assign(brandForm, { name: '', website: '', aliases: '' }); await refresh(); }
async function createPrompt() { await api.createPrompt({ ...promptForm, tags: promptForm.tags.split(',').map((x) => x.trim()).filter(Boolean) }); Object.assign(promptForm, { question: '', intent: 'commercial', priority: 50, tags: '' }); await refresh(); }
async function runDetection() { const brand = brands.value.find((item) => item.id === selectedBrand.value); if (!brand || !selectedPrompt.value) return; await api.detect({ promptId: selectedPrompt.value, provider: 'mock', brands: [{ id: brand.id, name: brand.name, aliases: brand.aliases, kind: 'brand' }] }); await refresh(); }
async function loadOpportunities() { if (opportunityBrand.value) opportunities.value = await api.opportunities(opportunityBrand.value); }
async function createContent() { await api.createContent({ brandId: contentForm.brandId, promptId: contentForm.promptId || null, title: contentForm.title, bodyMarkdown: contentForm.bodyMarkdown, evidenceUrls: contentForm.evidenceUrls.split(',').map((x) => x.trim()).filter(Boolean) }); Object.assign(contentForm, { brandId: '', promptId: '', title: '', bodyMarkdown: '', evidenceUrls: '' }); await refresh(); }
async function approveContent(id: string) { await api.setContentStatus(id, 'approved'); await refresh(); }
async function preparePublication() { const content = contents.value.find((item) => item.id === publishForm.contentId); if (!content) return; await api.createPublication({ ...publishForm, versionId: content.versions.at(-1)!.id }); await refresh(); }
async function previewExport() { if (!publishForm.contentId) return; exportPreview.value = (await api.exportContent(publishForm.contentId, publishForm.platform)).markdown; }
onMounted(refresh);
</script>

<template>
  <a-layout class="shell">
    <a-layout-sider width="224" theme="dark"><div class="brand"><span class="brand-mark">G</span><span>GEOv4</span></div><a-menu :selectedKeys="[active]" theme="dark" mode="inline" @select="({ key }: { key: string | number }) => active = String(key)"><a-menu-item v-for="item in menu" :key="item.key"><component :is="item.icon" /><span>{{ item.label }}</span></a-menu-item></a-menu></a-layout-sider>
    <a-layout><a-layout-header class="header"><div><strong>{{ title }}</strong><span class="crumb">真实数据 · 可追溯结果</span></div><a-button :loading="loading" @click="refresh">刷新数据</a-button></a-layout-header>
      <a-layout-content class="content"><a-alert v-if="error" :message="error" type="error" show-icon closable class="notice" />
        <template v-if="active === 'overview'">
          <section class="hero"><div><div class="eyebrow">AI SEARCH INTELLIGENCE</div><h1>从监测到增长机会</h1><p>所有指标都来自已持久化的真实检测；模拟数据不会污染生产指标。</p></div><a-button type="primary" size="large" @click="active = 'monitor'">运行检测</a-button></section>
          <a-row :gutter="16"><a-col :span="6"><a-card><div class="metric-label">有效检测</div><div class="metric-value">{{ summary.sampleSize }}</div><div class="metric-note">不含模拟数据</div></a-card></a-col><a-col :span="6"><a-card><div class="metric-label">品牌提及率</div><div class="metric-value">{{ summary.mentionRate === null ? '—' : `${Math.round(summary.mentionRate * 100)}%` }}</div><div class="metric-note">成功样本覆盖率</div></a-card></a-col><a-col :span="6"><a-card><div class="metric-label">平均排名</div><div class="metric-value">{{ summary.averageRank?.toFixed(1) ?? '—' }}</div><div class="metric-note">越低越好</div></a-card></a-col><a-col :span="6"><a-card><div class="metric-label">有效引用</div><div class="metric-value">{{ summary.citationCount }}</div><div class="metric-note">{{ summary.citationDomains.length }} 个来源域名</div></a-card></a-col></a-row>
          <a-empty v-if="!summary.sampleSize" description="创建品牌和 Prompt 后运行首次真实检测" class="empty-panel" />
        </template>
        <a-card v-else-if="active === 'brands'" title="品牌资产"><a-form layout="inline" class="toolbar" @submit.prevent="createBrand"><a-form-item><a-input v-model:value="brandForm.name" placeholder="品牌名称" /></a-form-item><a-form-item><a-input v-model:value="brandForm.website" placeholder="https://品牌官网" /></a-form-item><a-form-item><a-input v-model:value="brandForm.aliases" placeholder="别名，逗号分隔" /></a-form-item><a-button html-type="submit" type="primary" :disabled="!brandForm.name">添加品牌</a-button></a-form><a-table :dataSource="brands" rowKey="id" :pagination="false" :columns="[{title:'品牌',dataIndex:'name'},{title:'官网',dataIndex:'website'},{title:'别名',dataIndex:'aliases'},{title:'语言',dataIndex:'locale'}]" /></a-card>
        <a-card v-else-if="active === 'prompts'" title="Prompt 管理"><a-form layout="inline" class="toolbar" @submit.prevent="createPrompt"><a-form-item><a-input v-model:value="promptForm.question" placeholder="用户会向 AI 提什么问题？" class="question-input" /></a-form-item><a-form-item><a-select v-model:value="promptForm.intent" style="width:130px" :options="['informational','commercial','transactional','navigational'].map(value => ({value,label:value}))" /></a-form-item><a-form-item><a-input v-model:value="promptForm.tags" placeholder="标签，逗号分隔" /></a-form-item><a-button html-type="submit" type="primary" :disabled="!promptForm.question">添加 Prompt</a-button></a-form><a-table :dataSource="prompts" rowKey="id" :pagination="false" :columns="[{title:'问题',dataIndex:'question'},{title:'意图',dataIndex:'intent'},{title:'优先级',dataIndex:'priority'},{title:'标签',dataIndex:'tags'}]" /></a-card>
        <template v-else-if="active === 'monitor'"><a-card title="运行 AI 可见度检测" class="run-card"><a-space><a-select v-model:value="selectedPrompt" placeholder="选择 Prompt" style="width:360px" :options="prompts.filter(item => item.active).map(item => ({value:item.id,label:item.question}))" /><a-select v-model:value="selectedBrand" placeholder="选择品牌" style="width:220px" :options="brands.filter(item => !item.archived).map(item => ({value:item.id,label:item.name}))" /><a-button type="primary" :disabled="!selectedPrompt || !selectedBrand" @click="runDetection">运行可追溯模拟检测</a-button></a-space><div class="disclaimer">模拟结果明确标记 isMock=true，不计入真实可见度总览。</div></a-card><a-card title="检测记录"><a-table :dataSource="detections" rowKey="id" :columns="[{title:'Provider',dataIndex:'provider'},{title:'模型',dataIndex:'model'},{title:'状态',dataIndex:'status'},{title:'模拟',dataIndex:'isMock'},{title:'Prompt ID',dataIndex:'promptId'}]" /></a-card></template>
        <a-card v-else-if="active === 'opportunities'" title="竞争差距与机会"><a-space class="opportunity-filter"><a-select v-model:value="opportunityBrand" placeholder="选择要分析的品牌" style="width:260px" :options="brands.filter(item => !item.archived).map(item => ({value:item.id,label:item.name}))" /><a-button type="primary" :disabled="!opportunityBrand" @click="loadOpportunities">生成机会清单</a-button></a-space><a-alert message="机会分数 = 未提及率 × Prompt 优先级；没有真实样本时不生成伪分数。" type="info" show-icon class="notice" /><a-table :dataSource="opportunities" rowKey="promptId" :columns="[{title:'Prompt',dataIndex:'question'},{title:'意图',dataIndex:'intent'},{title:'样本',dataIndex:'sampleSize'},{title:'已提及',dataIndex:'mentionCount'},{title:'差距率',dataIndex:'gapRate'},{title:'机会分数',dataIndex:'score'}]" /></a-card>
        <template v-else-if="active === 'contents'"><a-card title="新建 GEO 内容" class="run-card"><a-form layout="vertical" @submit.prevent="createContent"><a-row :gutter="12"><a-col :span="6"><a-form-item label="品牌"><a-select v-model:value="contentForm.brandId" :options="brands.map(x => ({value:x.id,label:x.name}))" /></a-form-item></a-col><a-col :span="8"><a-form-item label="目标 Prompt"><a-select v-model:value="contentForm.promptId" allowClear :options="prompts.map(x => ({value:x.id,label:x.question}))" /></a-form-item></a-col><a-col :span="10"><a-form-item label="标题"><a-input v-model:value="contentForm.title" /></a-form-item></a-col></a-row><a-form-item label="Markdown 正文"><a-textarea v-model:value="contentForm.bodyMarkdown" :rows="8" /></a-form-item><a-form-item label="事实依据 URL（逗号分隔）"><a-input v-model:value="contentForm.evidenceUrls" /></a-form-item><a-button type="primary" html-type="submit" :disabled="!contentForm.brandId || !contentForm.title || contentForm.bodyMarkdown.length < 20">保存第一版</a-button></a-form></a-card><a-card title="内容版本与审核"><a-table :dataSource="contents" rowKey="id"><a-table-column title="标题" dataIndex="title" /><a-table-column title="状态" dataIndex="status" /><a-table-column title="版本"><template #default="{record}">v{{ record.versions.length }}</template></a-table-column><a-table-column title="操作"><template #default="{record}"><a-button size="small" :disabled="record.status === 'approved'" @click="approveContent(record.id)">审核通过</a-button></template></a-table-column></a-table></a-card></template>
        <template v-else><a-card title="四平台发布准备" class="run-card"><a-space wrap><a-select v-model:value="publishForm.contentId" placeholder="选择已审核内容" style="width:300px" :options="contents.filter(x => x.status === 'approved').map(x => ({value:x.id,label:x.title}))" /><a-select v-model:value="publishForm.platform" style="width:150px" :options="[{value:'zhihu',label:'知乎'},{value:'baijiahao',label:'百家号'},{value:'toutiao',label:'今日头条'},{value:'sohu',label:'搜狐号'}]" /><a-input v-model:value="publishForm.account" placeholder="发布账号" style="width:200px" /><a-button @click="previewExport">预览渠道稿</a-button><a-button type="primary" :disabled="!publishForm.contentId || !publishForm.account" @click="preparePublication">创建发布记录</a-button></a-space><a-textarea v-if="exportPreview" v-model:value="exportPreview" :rows="10" readonly class="export-preview" /></a-card><a-card title="发布记录"><a-table :dataSource="publications" rowKey="id" :columns="[{title:'平台',dataIndex:'platform'},{title:'账号',dataIndex:'account'},{title:'状态',dataIndex:'status'},{title:'文章URL',dataIndex:'canonicalUrl'}]" /></a-card></template>
      </a-layout-content></a-layout>
  </a-layout>
</template>
